//
// Created by mihael on 29/05/23.
//

#ifndef SAT_SOLVER_EXTENSIONS_H
#define SAT_SOLVER_EXTENSIONS_H

#define SUBSUMPTION
#define SUBSUMPTION_EXTENSION
#define IMPLICATION_GRAPH_WITH_BACKJUMPING

#endif //SAT_SOLVER_EXTENSIONS_H
