//
// Created by mihael on 29/05/23.
//

#ifndef SAT_SOLVER_EXTENSIONS_H
#define SAT_SOLVER_EXTENSIONS_H

#define SUBSUMPTION
#define IMPLICATION_GRAPH_WITH_BACKJUMPING
#define VARIABLE_STATE_INDEPENDENT_DECAYING_SUM

#endif //SAT_SOLVER_EXTENSIONS_H
